#!/bin/bash

ServoPin = 18
gpio -g mode ServoPin pwm

out_min = 800
out_max = 2300

function map(){
    # $1 = value
    # $2 = in_min
    # $3 = in_max
    # $4 = out_min
    # $5 = out_max
    val = ($1 - $2) * ($5 - $4) / ($3 - $2) + $4;
    return val
}

for i in `seq 3`; do
    gpio -g pwm ServoPin 0

done
